### ISSUE TITLE
How to create a single executable file(.exe) from python code on windows?

### ISSUE THREAD

**Issue by myd7349** [myd7349/Ongoing-Study#4]
I used to pack my python code as an executable file with [cx_Freeze](http://cx-freeze.sourceforge.net/). And when all thing was done, I may got a `.exe` file, plus with some `.pyd` and `.dll` files it depends.

The Windows version of official [NydusVPN](http://www.ny-dus.info/) client is written in Python. When I opened `NydusVPN.exe` with `Bandizip`/`7-zip`, I found that all the things is in this "archive": the `.pyc`, '.pyd' and the '.dll' files. WOW! Nice. Can I do the same thing with `cx_Freeze`?

The answer is NO:
[cx_Freeze FAQ - Single-file executables](http://cx-freeze.readthedocs.org/en/latest/faq.html)
>Single-file executables
>
cx_Freeze does not support building a single file exe, where all of the libraries for your application are embedded in one executable file.
>
>You can use IExpress to compress the build directory from cx_Freeze into a self-extracting archive: an exe which unpacks your application into a temporary directory and runs it. IExpress is a utility that’s included with Windows, intended for making installers, but it works equally well if you tell it to run the cx_Freeze-built exe after extraction.
>
>Alternatively, you can create a self extracting archive using 7zip. This is a bit more complex than using IExpress, but might provide more flexibility, and allows you to build your application using only open source tools.
 

**Solution 1**: cx_Freeze + [IExpress](http://en.wikipedia.org/wiki/IExpress)
<p></p>
**Solution 2**: cx_Freeze + [UPX](http://upx.sourceforge.net/) <sup>[[1]]</sup>
<p></p>
**Solution 3**: :star: [py2exe](http://www.py2exe.org/) <sup>[[2]]</sup> <sup>[[3]]</sup> <sup>[[4]]</sup>
<p>py2exe can be used in Python 3.x currently. And the size of this package is really small.</p>
**Solution 4**: [PyInstaller](https://github.com/pyinstaller/pyinstaller/wiki) <sup>[[3]]</sup>
<p>PyInstaller is large than py2exe and it needs [pywin32](http://sourceforge.net/projects/pywin32/)</p>

[1]: http://stackoverflow.com/questions/4999567/cx-freeze-python-single-file
[2]: http://stackoverflow.com/questions/1321708/creating-a-single-exe-file-from-python-code
[3]: http://stackoverflow.com/questions/112698/py2exe-generate-single-executable-file
[4]: http://stackoverflow.com/questions/1730742/pack-program-and-dynamically-loaded-files-into-single-executable-python-py

**Comment by myd7349** [comment]
This post mentioned `py2app`: [How to Create a Single Windows Executable from a Python and PyGame Project (Summary)](https://irwinkwan.com/2013/04/29/python-executables-pyinstaller-and-a-48-hour-game-design-compo/)

**Comment by myd7349** [comment]
https://github.com/PedramNavid/GooeyPi

**Comment by youbest2** [comment]
Pyinstaller can be used to generate a single executable file from a python project.
STEP 1 :
Install Pyinstaller
https://www.pyinstaller.org/downloads.html
https://github.com/pyinstaller/pyinstaller/zipball/develop

STEP 2 :
Extract the file in python installed directory (C:\Python27\)
Remane the extracted folder to : pyinstaller
STEP 3 :
Now open command prompt in Python directory and 
use command : cd pyinstaller
(To create exe)
use command : python pyinstaller.py your_python_file.py
(To create single exe)
use command : python pyinstaller.py --onefile --windowed your_python_file.py
(your_python_file.py : it should be placed in C:\Python27\pyinstaller\ )

Output Folde : C:\Python27\pyinstaller\main\dist\
